StylesPath = .vale/styles
MinAlertLevel = warning

Packages = Microsoft, proselint
Vocab = Blog

[src/posts/*.md]
BasedOnStyles = Vale, Microsoft, proselint

# too strict for personal blog writing
Microsoft.FirstPerson = NO
Microsoft.We = NO
Microsoft.Adverbs = NO
Microsoft.SentenceLength = NO
Microsoft.Passive = NO
Microsoft.Vocab = NO
Microsoft.GeneralURL = NO
Microsoft.Accessibility = NO
proselint.Annotations = NO
proselint.Very = NO
proselint.Typography = NO
proselint.Skunked = NO
Microsoft.Contractions = NO
Microsoft.Units = NO
Microsoft.HeadingAcronyms = NO
Microsoft.Ellipses = NO

Vale.Spelling = YES
Vale.Terms = YES
